services:
  docker_app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file: .env
    volumes:
      - .:/app
      - ~/.ssh:/root/.ssh:ro
      - ./docker/conf/php.ini:/usr/local/etc/php/conf.d/app.ini
      - ./docker/conf/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/conf/apache.conf:/etc/apache2/conf-available/z-app.conf
      # Themes
      - ../../WP-themes/${THEME_NAME}:/app/wp-content/themes/${THEME_NAME}
      # Plugins
      - ../../WP-plugins/acf-barcodescanner:/app/wp-content/plugins/acf-barcodescanner
      # Named volumes for dependencies (fixes permission issues)
      - theme-node-modules:/app/wp-content/themes/${THEME_NAME}/node_modules
      - theme-vendor:/app/wp-content/themes/${THEME_NAME}/vendor
    labels:
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${APP_FQDN}`)"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=http"
      - "traefik.http.services.${PROJECT_NAME}.loadbalancer.server.port=80"
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - THEME_NAME=${THEME_NAME}
      - GIT_USER_NAME=${GIT_USER_NAME:-}
      - GIT_USER_EMAIL=${GIT_USER_EMAIL:-}
    networks:
      - traefik
      - app-network

volumes:
  theme-node-modules:
  theme-vendor: # if composer is used

networks:
  app-network:
    driver: bridge
  traefik:
    external: true
